site_name: مستندات پروژه من
site_url: https://mohammadsafyar.github.io/docs/
nav:
  - خانه: index.md
  - راه‌اندازی: setup.md
theme:
  name: material
  language: fa
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: حالت تاریک
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: حالت روشن
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
