site_name: Project Documentation
site_url: https://mohammadsafyar.github.io/docs/

nav:
  - Home: index.md
  - SQL Server:
      - Backup: sql-server/backup.md
theme:
  name: material
  language: en

  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
